<?php
    header('Content-Type: application/json');
    header('Access-Control-Allow-Origin: *');
?>

[{
  "id": 1,
  "nome_fantasia": "MEU ambiente",
  "razao_social": "LTDA",
  "cnpj": "11.587.764/0001-41",
  "categoria_id": "Meio Ambiente",
  "telefone": "5918337686",
  "email": "snoice0@studiopress.com",
  "cep": "23132-232",
  "endereco": "RUA GENERAL CHAGAS SANTOS",
  "numero_endereco": 88,
  "bairro": "JARDIM - SANTO ANDRE",
  "cidade": "Arame",
  "uf": "TO"
}, {
  "id": 2,
  "nome_fantasia": "ClikeDecore",
  "razao_social": "EPP",
  "cnpj": "74.918.397/0001-31",
  "categoria_id": "Móveis e Decoração",
  "telefone": "7203381097",
  "email": "rough1@latimes.com",
  "cep": "54545-656",
  "endereco": "RUAS DAS BANDEIRAS",
  "numero_endereco": 32,
  "bairro": "CID JULIA",
  "cidade": "São Pedro da Água Branca",
  "uf": "DF"
}, {
  "id": 3,
  "nome_fantasia": "Design de Ambiente",
  "razao_social": "ME",
  "cnpj": "12.859.886/0001-02",
  "categoria_id": "Objetos Decorativos",
  "telefone": "1926968766",
  "email": "ptattersill2@toplist.cz",
  "cep": "56545-444",
  "endereco": "Av NOSSA SRÂª. DAS VITORIAS",
  "numero_endereco": 21,
  "bairro": "CENTRO",
  "cidade": "Cidelândia",
  "uf": "TO"
}, {
  "id": 4,
  "nome_fantasia": "Decor4me",
  "razao_social": "S.A.",
  "cnpj": "27.161.663/0001-44",
  "categoria_id": "Objetos Decorativos",
  "telefone": "7098667078",
  "email": "tsepey3@wordpress.com",
  "cep": "45456-456",
  "endereco": "RUA GASSIPOS",
  "numero_endereco": 71,
  "bairro": "VILA MARIANA",
  "cidade": "Buriti",
  "uf": "ES"
}, {
  "id": 5,
  "nome_fantasia": "Harmoniza",
  "razao_social": "LTDA",
  "cnpj": "11.587.764/0001-41",
  "categoria_id": "Móveis para Sala",
  "telefone": "9491311037",
  "email": "scurner4@histats.com",
  "cep": "16521-123",
  "endereco": "AVEN LINS DE VASCONCELOS",
  "numero_endereco": 38,
  "bairro": "JARDIM - SANTO ANDRE",
  "cidade": "São Francisco do Maranhão",
  "uf": "MS"
}, {
  "id": 6,
  "nome_fantasia": "Projeto Ambiente",
  "razao_social": "EPP",
  "cnpj": "74.918.397/0001-31",
  "categoria_id": "Engenharia e Projetos",
  "telefone": "2537765719",
  "email": "squilter5@skype.com",
  "cep": "23132-232",
  "endereco": "R TOMAS DE SOUZA",
  "numero_endereco": 38,
  "bairro": "CID JULIA",
  "cidade": "São Bento",
  "uf": "GO"
}, {
  "id": 7,
  "nome_fantasia": "DECORideias",
  "razao_social": "ME",
  "cnpj": "12.859.886/0001-02",
  "categoria_id": "Móveis e Decoração",
  "telefone": "3334401860",
  "email": "nharget6@behance.net",
  "cep": "54545-656",
  "endereco": "RUA GENERAL CHAGAS SANTOS",
  "numero_endereco": 92,
  "bairro": "CENTRO",
  "cidade": "Montes Altos",
  "uf": "RO"
}, {
  "id": 8,
  "nome_fantasia": "For you decoration",
  "razao_social": "S.A.",
  "cnpj": "27.161.663/0001-44",
  "categoria_id": "Canecas e Squeezes",
  "telefone": "7123026618",
  "email": "dmanuaud7@about.me",
  "cep": "56545-444",
  "endereco": "RUAS DAS BANDEIRAS",
  "numero_endereco": 19,
  "bairro": "VILA MARIANA",
  "cidade": "Cajari",
  "uf": "PI"
}, {
  "id": 9,
  "nome_fantasia": "Design by me",
  "razao_social": "LTDA",
  "cnpj": "11.587.764/0001-41",
  "categoria_id": "Cortinas e Persianas",
  "telefone": "6884677560",
  "email": "odunston8@google.ca",
  "cep": "45456-456",
  "endereco": "Av NOSSA SRÂª. DAS VITORIAS",
  "numero_endereco": 11,
  "bairro": "JARDIM - SANTO ANDRE",
  "cidade": "Cururupu",
  "uf": "SC"
}, {
  "id": 10,
  "nome_fantasia": "MYhome",
  "razao_social": "EPP",
  "cnpj": "74.918.397/0001-31",
  "categoria_id": "Consórcio Imóveis",
  "telefone": "5252662025",
  "email": "gdewhirst9@cdbaby.com",
  "cep": "16521-123",
  "endereco": "RUA GASSIPOS",
  "numero_endereco": 88,
  "bairro": "CID JULIA",
  "cidade": "Nova Olinda do Maranhão",
  "uf": "PI"
}]