<?php
    header('Content-Type: application/json');
    header('Access-Control-Allow-Origin: *');
?>
{"data":
    [{
	  "id": 1,
	  "produto": "grampeador",
	  "quantidade": 97,
	  "funcionario": "GRAZIELLE GOES MACIEL",
	  "setor": "Comercial",
	  "data": "11/11/2017",
	  "status": "Aprovado",
	  "status_compra": "Comprado",
	  "status_cotacao": "A cotar",
	  "preco": "37.21",
	  "fornecedor": "DECORideias"
	}, {
	  "id": 2,
	  "produto": "lâmpada de mesa",
	  "quantidade": 6,
	  "funcionario": "MARCIO DE MENDONCA MANCINE DANTAS",
	  "setor": "Executivo",
	  "data": "26/10/2017",
	  "status": "Pendente",
	  "status_compra": "Comprado",
	  "status_cotacao": "Em cotação",
	  "preco": "40.00",
	  "fornecedor": "Harmoniza"
	}, {
	  "id": 3,
	  "produto": "borracha",
	  "quantidade": 40,
	  "funcionario": "REBECA SANTHELENA",
	  "setor": "Administrativo",
	  "data": "07/10/2017",
	  "status": "Aprovado",
	  "status_compra": "Comprado",
	  "status_cotacao": "A cotar",
	  "preco": "17.49",
	  "fornecedor": "Decor4me"
	}, {
	  "id": 4,
	  "produto": "borracha",
	  "quantidade": 66,
	  "funcionario": "GABRIELA DENISE DE ARAUJO",
	  "setor": "Administrativo",
	  "data": "03/11/2017",
	  "status": "Aprovado",
	  "status_compra": "Pendente",
	  "status_cotacao": "Cotado",
	  "preco": "26.59",
	  "fornecedor": "MEU ambiente"
	}, {
	  "id": 5,
	  "produto": "lápis",
	  "quantidade": 16,
	  "funcionario": "ALEXSANDRA MELO DOS SANTOS",
	  "setor": "Executivo",
	  "data": "02/12/2017",
	  "status": "Pendente",
	  "status_compra": "Comprado",
	  "status_cotacao": "Em cotação",
	  "preco": "43.83",
	  "fornecedor": "ClikeDecore"
	}, {
	  "id": 6,
	  "produto": "cadeira giratória",
	  "quantidade": 94,
	  "funcionario": "HELENA LARA FÉRA",
	  "setor": "Executivo",
	  "data": "02/11/2017",
	  "status": "Aprovado",
	  "status_compra": "Pendente",
	  "status_cotacao": "A cotar",
	  "preco": "26.43",
	  "fornecedor": "MYhome"
	}, {
	  "id": 7,
	  "produto": "cadeira giratória",
	  "quantidade": 91,
	  "funcionario": "DANIEL YAN CHAO",
	  "setor": "Gestão de Pessoas",
	  "data": "12/12/2017",
	  "status": "Aprovado",
	  "status_compra": "Pendente",
	  "status_cotacao": "Em cotação",
	  "preco": "25.78",
	  "fornecedor": "For you decoration"
	}, {
	  "id": 8,
	  "produto": "régua geométrica",
	  "quantidade": 31,
	  "funcionario": "WANIA GOMES BARBOSA",
	  "setor": "Administrativo",
	  "data": "29/10/2017",
	  "status": "Aprovado",
	  "status_compra": "Comprado",
	  "status_cotacao": "Em cotação",
	  "preco": "48.16",
	  "fornecedor": "ClikeDecore"
	}, {
	  "id": 9,
	  "produto": "grampeador",
	  "quantidade": 17,
	  "funcionario": "MÁRCIO DANTAS",
	  "setor": "Administrativo",
	  "data": "04/11/2017",
	  "status": "Pendente",
	  "status_compra": "Comprado",
	  "status_cotacao": "A cotar",
	  "preco": "25.87",
	  "fornecedor": "ClikeDecore"
	}, {
	  "id": 10,
	  "produto": "cadeira giratória",
	  "quantidade": 55,
	  "funcionario": "CLAUDETE APARECIDA REZENDE HENRIQUE",
	  "setor": "Executivo",
	  "data": "19/10/2017",
	  "status": "Pendente",
	  "status_compra": "Pendente",
	  "status_cotacao": "Em cotação",
	  "preco": "49.15",
	  "fornecedor": "MYhome"
	}, {
	  "id": 11,
	  "produto": "caderno de notas",
	  "quantidade": 39,
	  "funcionario": "RENATA MARGARIDA DOS SANTOS",
	  "setor": "Gestão de Pessoas",
	  "data": "14/11/2017",
	  "status": "Pendente",
	  "status_compra": "Comprado",
	  "status_cotacao": "A cotar",
	  "preco": "47.18",
	  "fornecedor": "DECORideias"
	}, {
	  "id": 12,
	  "produto": "pasta",
	  "quantidade": 60,
	  "funcionario": "RENATA PIMENTA GALA",
	  "setor": "Executivo",
	  "data": "07/11/2017",
	  "status": "Aprovado",
	  "status_compra": "Pendente",
	  "status_cotacao": "A cotar",
	  "preco": "44.61",
	  "fornecedor": "design by me"
	}, {
	  "id": 13,
	  "produto": "fichário",
	  "quantidade": 15,
	  "funcionario": "MARCIO DE MENDONCA MANCINE DANTAS",
	  "setor": "Comercial",
	  "data": "24/11/2017",
	  "status": "Pendente",
	  "status_compra": "Comprado",
	  "status_cotacao": "Em cotação",
	  "preco": "12.98",
	  "fornecedor": "For you decoration"
	}, {
	  "id": 14,
	  "produto": "pasta",
	  "quantidade": 48,
	  "funcionario": "MARCIO",
	  "setor": "Marketing",
	  "data": "15/11/2017",
	  "status": "Pendente",
	  "status_compra": "Pendente",
	  "status_cotacao": "A cotar",
	  "preco": "47.37",
	  "fornecedor": "ClikeDecore"
	}, {
	  "id": 15,
	  "produto": "borracha",
	  "quantidade": 63,
	  "funcionario": "GISLAINE DOS SANTOS",
	  "setor": "Executivo",
	  "data": "10/12/2017",
	  "status": "Aprovado",
	  "status_compra": "Comprado",
	  "status_cotacao": "Cotado",
	  "preco": "16.69",
	  "fornecedor": "DECORideias"
	}, {
	  "id": 16,
	  "produto": "cadeira giratória",
	  "quantidade": 100,
	  "funcionario": "VIRGINIA DOS PASSOS CALVACANTE",
	  "setor": "T.I. Contábil",
	  "data": "05/12/2017",
	  "status": "Aprovado",
	  "status_compra": "Comprado",
	  "status_cotacao": "Cotado",
	  "preco": "23.73",
	  "fornecedor": "ClikeDecore"
	}, {
	  "id": 17,
	  "produto": "fichário",
	  "quantidade": 4,
	  "funcionario": "INDEFINIDO",
	  "setor": "Administrativo",
	  "data": "11/12/2017",
	  "status": "Aprovado",
	  "status_compra": "Pendente",
	  "status_cotacao": "Em cotação",
	  "preco": "16.73",
	  "fornecedor": "DECORideias"
	}, {
	  "id": 18,
	  "produto": "régua",
	  "quantidade": 73,
	  "funcionario": "ClinicWeb",
	  "setor": "T.I. Contábil",
	  "data": "06/10/2017",
	  "status": "Aprovado",
	  "status_compra": "Comprado",
	  "status_cotacao": "Em cotação",
	  "preco": "30.37",
	  "fornecedor": "ClikeDecore"
	}, {
	  "id": 19,
	  "produto": "cadeira giratória",
	  "quantidade": 24,
	  "funcionario": "GRAZIELLE GOES MACIEL",
	  "setor": "Gestão de Pessoas",
	  "data": "06/10/2017",
	  "status": "Aprovado",
	  "status_compra": "Pendente",
	  "status_cotacao": "Em cotação",
	  "preco": "38.89",
	  "fornecedor": "DECORideias"
	}, {
	  "id": 20,
	  "produto": "cadeira giratória",
	  "quantidade": 15,
	  "funcionario": "VIRGINIA DOS PASSOS CALVACANTE",
	  "setor": "T.I. Contábil",
	  "data": "06/10/2017",
	  "status": "Pendente",
	  "status_compra": "Pendente",
	  "status_cotacao": "Em cotação",
	  "preco": "35.54",
	  "fornecedor": "Projeto Ambiente"
	}, {
	  "id": 21,
	  "produto": "clipes",
	  "quantidade": 40,
	  "funcionario": "ROBERTA CORREA SARAGIOTTO",
	  "setor": "Executivo",
	  "data": "21/09/2017",
	  "status": "Pendente",
	  "status_compra": "Comprado",
	  "status_cotacao": "Em cotação",
	  "preco": "42.03",
	  "fornecedor": "Projeto Ambiente"
	}, {
	  "id": 22,
	  "produto": "cartucho de impressora",
	  "quantidade": 94,
	  "funcionario": "JOSÉ POSSIDONIO BEZERRA",
	  "setor": "Administrativo",
	  "data": "27/09/2017",
	  "status": "Pendente",
	  "status_compra": "Pendente",
	  "status_cotacao": "A cotar",
	  "preco": "36.13",
	  "fornecedor": "ClikeDecore"
	}, {
	  "id": 23,
	  "produto": "cadeira giratória",
	  "quantidade": 3,
	  "funcionario": "ROBERTO CARLOS CASSAB BROLIO",
	  "setor": "Comercial",
	  "data": "13/10/2017",
	  "status": "Pendente",
	  "status_compra": "Pendente",
	  "status_cotacao": "Em cotação",
	  "preco": "42.87",
	  "fornecedor": "Decor4me"
	}, {
	  "id": 24,
	  "produto": "livro-caixa",
	  "quantidade": 79,
	  "funcionario": "ROBERTA CORREA SARAGIOTTO",
	  "setor": "Gestão de Pessoas",
	  "data": "11/10/2017",
	  "status": "Pendente",
	  "status_compra": "Pendente",
	  "status_cotacao": "A cotar",
	  "preco": "20.58",
	  "fornecedor": "ClikeDecore"
	}, {
	  "id": 25,
	  "produto": "pasta",
	  "quantidade": 86,
	  "funcionario": "TESTE",
	  "setor": "Gestão de Pessoas",
	  "data": "10/12/2017",
	  "status": "Aprovado",
	  "status_compra": "Comprado",
	  "status_cotacao": "Em cotação",
	  "preco": "40.22",
	  "fornecedor": "DECORideias"
	}]
}